pkg/apis/settings/v1alpha1/handler_application.go
pkg/apis/settings/v1alpha1/register.go
pkg/app_service/v1/client.go

/kind feature
add application permissions api for settings
Fixes #
```release-note
```

feat: add application permissions api for settings

---

pkg/apis/settings/v1alpha1/handler_application.go
pkg/apis/settings/v1alpha1/register.go
pkg/app_service/v1/client.go

feat: add get provider registry list by appname api

feat: get provider registry list by appname

---

pkg/apis/settings/v1alpha1/handler_application.go
pkg/apis/settings/v1alpha1/register.go
pkg/app_service/v1/client.go

add support for nats mesage queue

feat: add support for nats

---

pkg/apis/app_process/v1alpha1/handler.go
pkg/apis/app_process/v1alpha1/register.go
pkg/apis/base.go
pkg/app_service/v1/client.go

feat: return all user's app for admin

feat: return all user's app for admin

---

pkg/apis/iam/v1alpha1/handler.go

fix: confused username in user create func

fix: confused username in user create

---

pkg/apis/iam/v1alpha1/handler.go

fix: add check allocate pod for user create

fix: add check allocate pod for user create

---

pkg/apis/settings/v1alpha1/handler.go
pkg/apis/settings/v1alpha1/model.go
pkg/apis/settings/v1alpha1/register.go
pkg/constants/constants.go

feat: add theme for system config

feat: add theme for system config

---

config/ingress/nginx.tmpl
internal/ingress/api/app.bytetrade.io/v1alpha1/application_types.go
internal/ingress/controllers/config/config.go
internal/ingress/controllers/nginx.go

feat: inject window push state script

feat: inject window push state script

---

pkg/apis/settings/v1alpha1/handler.go
pkg/apis/settings/v1alpha1/model.go

fix: set default theme to light

fix: set default theme to light

---

pkg/apis/iam/v1alpha1/handler.go

fix: remove wizard deployment after active

fix: remove wizard deployment after active

---

config/ingress/nginx.tmpl
internal/ingress/controllers/config/config.go
internal/ingress/controllers/controllers.go
internal/ingress/controllers/nginx.go

feat: inject terminus language meta info

feat: inject terminus language meta info

---

cmd/ingress/main.go
internal/ingress/controllers/controllers.go

fix: update nginx.conf when user language changed

fix: update nginx.conf when user language changed

---

pkg/apis/monitor/v1alpha1/handler.go

fix: unify cluster metrics unit

fix: cluster metrics unit

---

internal/ingress/controllers/nginx.go

fix: add meta terminus language for desktop

fix: add meta terminus language for desktop

---

pkg/app_service/v1/internal.go
pkg/app_service/v1/types.go

feat: add entrance state for app

feat: add entrance state for app

---

config/ingress/nginx.tmpl
internal/ingress/api/app.bytetrade.io/v1alpha1/application_types.go
internal/ingress/controllers/config/config.go
internal/ingress/controllers/controllers.go

feat: add udp support

---

cmd/apiserver/app/watch_entrance_ip.go
internal/ingress/controllers/config/config.go

fix: support http2

---

internal/ingress/controllers/config/config.go

fix: add application/x-mpegURL gzip types

fix: add application/x-mpegURL gzip types

---

pkg/apis/settings/v1alpha1/handler.go

some errors are not assigned to the function-level `err` in the `handleEnableHTTPS` handler, which causes the deferred function not setting the activation status to failed, and the frontend will stuck at the activation page without retry.

fix: set failed activation status upon all errors

---

pkg/app_service/v1/types.go

fix: return user apps invisible field while false

fix: return user apps invisible field while false

---

pkg/app_service/v1/internal.go
pkg/app_service/v1/types.go

feat: add ports and tailscale acl to myapps

feat: add ports and tailscale acl to myapps

---

pkg/apis/settings/v1alpha1/model.go

fix: set priority class for l4 proxy

fix: set priority class for l4 proxy

---

cmd/apiserver/app/server.go
cmd/apiserver/app/watch_entrance_ip.go
pkg/apis/iam/v1alpha1/operator/user_operator.go
pkg/apis/settings/v1alpha1/handler.go
pkg/apis/settings/v1alpha1/reverseproxyconf.go
pkg/constants/constants.go
pkg/watchers/reverse_proxy/reverse_proxy.go

this is a cherry pick of https://github.com/beclab/bfl/pull/70

feat: add watcher to apply reverse proxy(#70)

---

pkg/apis/settings/v1alpha1/reverseproxyconf.go

this is a cherry pick of https://github.com/beclab/bfl/pull/79

fix: fetch current user object before every configure operation (#79)

---

pkg/apis/iam/v1alpha1/handler.go

fix: create user cpu check

---

Dockerfile.frpc

this is a cherry pick of https://github.com/beclab/bfl/pull/83

feat: add error log to frpc (#83)

---

pkg/apis/settings/v1alpha1/handle_headscale.go
pkg/apis/settings/v1alpha1/register.go
pkg/client/dynamic_client/apps/application.go

feat: tailscale subnet
